### PR TITLE
feat: snackbar added

### PR DESCRIPTION
**Pull request by sonishreyas**
## Change Logs

Snackbar added

## Screenshot
image

## Preview Link
https://deploy-preview-15--ripple-ui.netlify.app/components/snackbars/snackbars.html

### CODE REVIEW

**Review by ravikumar0403 — COMMENTED** [review]
looks good. Just a observation, The `center` snackbars are not exactly in center. it starts from center of viewport

**Review by nyyshaaa — COMMENTED** [review]
center ones don't come in exact center, good to merge!

**Review by rishmi5h — COMMENTED** [review]
looks good, just center rest all are fine.

**Comment by sonishreyas** [comment]
I tried the centering issue but it still does not come in center will look into it after finishing assignments

**Pull request merged**
