### PR TITLE
feat: modals added

### PR DESCRIPTION
**Pull request by sonishreyas**
## Change Logs
Feature: Modals added into component library

## Screenshots
image

## Preview Link

https://deploy-preview-12--ripple-ui.netlify.app/components/modals/modals.html

### CODE REVIEW

**Comment by parthpandyappp** [comment]
Looks good to me. Talking about the UX, the user has to scroll up to the top of the page to fill in the details. Instead, you can apply a `next` button and make a compact sized modal. Although, it's when UX matter, otherwise rest LGTM.

**Review by yashpatel1797 — APPROVED** [review]
The code looks good to me. The design looks good great work.

**Comment by sonishreyas** [comment]
> Looks good to me. Talking about the UX, the user has to scroll up to the top of the page to fill in the details. Instead, you can apply a `next` button and make a compact sized modal. Although, it's when UX matter, otherwise rest LGTM.

Thanks will look into this later

**Review by parthpandyappp — COMMENTED** [review]
approved

**Pull request merged**
